### Login to obtain JWT token
# @name tokenAPI
POST http://localhost:5287/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

@jwt_token = {{tokenAPI.response.body.token}}

### Get user
GET http://localhost:5287/user/
Authorization: Bearer {{jwt_token}}