FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source
COPY bookservice/ ./bookservice/
WORKDIR /source/bookservice
RUN dotnet restore
RUN dotnet publish -c release -o /app --no-restore

# runs it using aspnet runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./

# Set the environment variable to listen on port 5287
ENV ASPNETCORE_URLS=http://+:5287

# Expose port 5287
EXPOSE 5287
ENTRYPOINT ["dotnet", "bookservice.dll"]