# Stage 1: Build Stage
FROM node:18 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY bookservice-client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY bookservice-client .

# Build the application
RUN npm run build

# Stage 2: Production Stage
FROM nginx:alpine

# Copy the built application from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom Nginx configuration file
COPY bookservice-client/nginx.conf /etc/nginx/nginx.conf

# Expose port 3000
EXPOSE 3000

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]